export enum QUERY_KEYS {
  CATEGORY_LIST = "CATEGORY_LIST",
  CATEGORY_DETAIL = "CATEGORY_DETAIL",
  ACTOR_LIST = "ACTOR_LIST",
  ACTOR_DETAIL = "ACTOR_DETAIL",
  MOVIE_LIST = "MOVIE_LIST",
  MOVIE_DETAIL = "MOVIE_DETAIL",
}
